### PR TITLE
countdown colors added

### PR DESCRIPTION
**Pull request by Aech27**

### CODE REVIEW

**Comment by Reikimann** [comment]
@Aech27 Could you provide a picture?

**Comment by Aech27** [comment]
> @Aech27 Could you provide a picture?

Shure, but it'll be a few days

**Comment by Aech27** [comment]
Screenshot from 2023-11-18 18-24-00

**Comment by logicguy1** [comment]
Countdown colors on dashboard?

**Comment by Reikimann** [comment]
image

I just made a change so that assignments are only colored if they aren't delivered :)

**Comment by Reikimann** [comment]
> Countdown colors on dashboard?

Not yet, but that would be cool! I've already implemented the required functions, so you would just need to query the delivery date :D

**Pull request merged**
